stages:
  - test
  - sonarqube
  - docker
  - scan
  - publish

unit_test:
  image: python:3.12
  stage: test
  script:
    - cd backend
    - pip install -r requirements.txt
    - python -m unittest test_app.py

sonarqube-check:
  stage: sonarqube
  tags:
    - macos
  script:
    - docker run --rm
      -e SONAR_HOST_URL="$SONAR_HOST_URL"
      -e SONAR_TOKEN="$SONAR_TOKEN"
      -v "$CI_PROJECT_DIR:/usr/src"
      sonarsource/sonar-scanner-cli

docker-build:
  stage: docker
  tags:
    - macos
  script:
    - docker build -t claims-backend:$CI_COMMIT_SHORT_SHA ./backend

trivy-scan:
  stage: scan
  tags:
    - macos
  script:
    - export PATH="/opt/homebrew/bin:$PATH"
    - trivy image --exit-code 0 --severity HIGH,CRITICAL claims-backend:$CI_COMMIT_SHORT_SHA

publish-image:
  stage: publish
  tags:
    - macos
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker tag claims-backend:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
